[package]
name = "simple-socks5-proxy-core"
version = "0.1.0"
edition = "2021"

[dependencies]
log = { workspace = true }
anyhow = "1"
tokio = { version = "1", features = ["full"] }
socks5-impl = "0.5"
russh = "0.45.0"
async-trait = "0.1"